// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SolutionReferences.Data;

namespace SolutionReferences.Data.Migrations
{
    [DbContext(typeof(SolutionReferencesDb))]
    [Migration("20210216234822_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("ProjectReference", b =>
                {
                    b.Property<string>("ProjectsProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferencesReferenceId")
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectsProjectId", "ReferencesReferenceId");

                    b.HasIndex("ReferencesReferenceId");

                    b.ToTable("ProjectReference");
                });

            modelBuilder.Entity("ProjectSolution", b =>
                {
                    b.Property<string>("ProjectsProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SolutionsSolutionId")
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectsProjectId", "SolutionsSolutionId");

                    b.HasIndex("SolutionsSolutionId");

                    b.ToTable("ProjectSolution");
                });

            modelBuilder.Entity("SolutionReferences.Data.Models.Project", b =>
                {
                    b.Property<string>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssemblyFileVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssemblyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssemblyVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectType")
                        .HasColumnType("TEXT");

                    b.Property<string>("RootNamespace")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetFramework")
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("SolutionReferences.Data.Models.Reference", b =>
                {
                    b.Property<string>("ReferenceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenceType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferencedProjectProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .HasColumnType("TEXT");

                    b.HasKey("ReferenceId");

                    b.HasIndex("ReferencedProjectProjectId");

                    b.ToTable("References");
                });

            modelBuilder.Entity("SolutionReferences.Data.Models.Solution", b =>
                {
                    b.Property<string>("SolutionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("MinimumVisualStudioVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("SolutionType")
                        .HasColumnType("TEXT");

                    b.Property<string>("SolutionTypeVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("VisualStudioFormatVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("VisualStudioSolutionFileVersion")
                        .HasColumnType("TEXT");

                    b.HasKey("SolutionId");

                    b.ToTable("Solutions");
                });

            modelBuilder.Entity("ProjectReference", b =>
                {
                    b.HasOne("SolutionReferences.Data.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectsProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SolutionReferences.Data.Models.Reference", null)
                        .WithMany()
                        .HasForeignKey("ReferencesReferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectSolution", b =>
                {
                    b.HasOne("SolutionReferences.Data.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectsProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SolutionReferences.Data.Models.Solution", null)
                        .WithMany()
                        .HasForeignKey("SolutionsSolutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SolutionReferences.Data.Models.Reference", b =>
                {
                    b.HasOne("SolutionReferences.Data.Models.Project", "ReferencedProject")
                        .WithMany()
                        .HasForeignKey("ReferencedProjectProjectId");

                    b.Navigation("ReferencedProject");
                });
#pragma warning restore 612, 618
        }
    }
}
